[project]
name = "safespace-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
    "streamlit>=1.48.1",
    "uvicorn>=0.35.0",
]
